from gpiozero import LED
from time import sleep
import psutil
import random


# Define GPIO pins for each segment
a = LED(25)
b = LED(24)
c = LED(22)
d = LED(27)
e = LED(4)
f = LED(26)
g = LED(13)


greenled= LED(20)

while True:
    cpu_usage = psutil.cpu_percent(interval = 1, percpu = True)
    cpu_usage_mean = sum([i/len(cpu_usage) for i in cpu_usage])
    cpu_usage_mean = round(cpu_usage_mean, 3)
    print(f'CPU Usage Mean: {cpu_usage_mean}')
    #num = int(cpu_usage_mean)
    num = random.randint(0, 10)
    print(f'CPU Usage Num: {num}')
    if num == 0:
        a.on()
        b.on()
        c.on()
        d.on()
        e.on()
        f.on()
        g.off()
        greenled.off()
    elif num == 1:
        a.off()
        b.off()
        c.off()
        d.off()
        e.on()
        f.on()
        g.off()
        greenled.off()
    elif num == 2:
        a.on()
        b.on()
        c.off()
        d.on()
        e.on()
        f.off()
        g.on()
        greenled.off()
    elif num == 3:
        a.on()
        b.on()
        c.on()
        d.on()
        e.off()
        f.off()
        g.on()
        greenled.off()
    elif num == 4:
        a.off()
        b.on()
        c.on()
        d.off()
        e.off()
        f.on()
        g.on()
        greenled.off()
    elif num == 5:
        a.on()
        b.off()
        c.on()
        d.on()
        e.off()
        f.on()
        g.on()
        greenled.off()
    elif num == 6:
        a.on()
        b.off()
        c.on()
        d.on()
        e.on()
        f.on()
        g.on()
        greenled.off()
    elif num == 7:
        a.on()
        b.on()
        c.on()
        d.off()
        e.off()
        f.off()
        g.off()
        greenled.off()
    elif num == 8:
        a.on()
        b.on()
        c.on()
        d.on()
        e.on()
        f.on()
        g.on()
        greenled.off()
    elif num == 9:
        a.on()
        b.on()
        c.on()
        d.on()
        e.off()
        f.on()
        g.on()
        greenled.off()
    else:
        greenled.on()
        a.off()
        b.off()
        c.off()
        d.off()
        e.off()
        f.off()
        g.off()
    sleep(1)
